export function foo() {
  if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
  } else if (0) {
    ""
  }
}
